name: DevSecOps Pipeline - SonarCloud Focus
on:
  push:
    branches:
      - feature/devsecops-pipeline
permissions:
  contents: read
jobs:
  ci-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Sonar token access
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          set -e
          curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/projects/search?projects=sweat8_devsecops-laboratorio" | tee /tmp/p.json
          grep -q '"total":[1-9]' /tmp/p.json
          curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=sweat8_devsecops-laboratorio" | grep -q '"projectStatus"'

      - name: SonarCloud Scan (SAST)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=sweat8
            -Dsonar.projectKey=sweat8_devsecops-laboratorio
            -Dsonar.qualitygate.wait=true

      - name: Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DevSecOpsLab'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 4.0

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

      - name: Build Docker image
        run: docker build -t movies-app:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'movies-app:${{ github.sha }}'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'
