name: DevSecOps Pipeline - SonarCloud Focus
on:
  push:
    branches:
      - feature/devsecops-pipeline
permissions:
  contents: read
jobs:
  ci-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- SAST ----------
      - name: SonarCloud Scan (SAST)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=sweat8
            -Dsonar.projectKey=sweat8_devsecops-laboratorio
            -Dsonar.qualitygate.wait=true

      # ---------- SCA ----------
      - name: Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DevSecOpsLab'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 4.0  # ES: falla si existe vulnerabilidad CVSS >= 4.0 (MEDIUM)

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

      # ---------- Build Docker ----------
      - name: Build Docker image
        run: docker build -t movies-app:${{ github.sha }} .

      # ---------- Image Security (Trivy) ----------
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'movies-app:${{ github.sha }}'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'