name: DevSecOps Pipeline

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    name: SAST - SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan (branches)
        if: github.ref != 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=sweat8
            -Dsonar.projectKey=sweat8_devsecops-laboratorio

      - name: SonarCloud Scan + Quality Gate (main)
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=sweat8
            -Dsonar.projectKey=sweat8_devsecops-laboratorio
            -Dsonar.qualitygate.wait=true

  sca:
    name: SCA - Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DevSecOpsLab'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Fail if vulnerabilities >= MEDIUM
        run: |
          if grep -Ei 'CRITICAL|HIGH|MEDIUM' reports/dependency-check-report.html; then
            echo 'Dependency vulnerabilities found (>= MEDIUM).'
            exit 1
          else
            echo 'No dependency vulnerabilities >= MEDIUM'
          fi

      - name: Upload SCA report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

  image-security:
    name: Image Security - Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app:latest .

      - name: Trivy scan (generate SARIF)
        id: trivy
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'app:latest'
          format: 'sarif'
          output: 'trivy.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'

      - name: Upload Trivy SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Upload Trivy artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy.sarif

      - name: Fail job if Trivy found vulnerabilities
        if: steps.trivy.outcome == 'failure'
        run: exit 1
